steps:
  # Step 1: Set up the environment
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Setting up environment variables"
        gcloud config set project $PROJECT_ID
        gcloud auth configure-docker

  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/aurora-humans-container:latest'
      - '.'

  # Step 3: Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/aurora-humans-container:latest'

  # Step 4: Deploy the image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'aurora-humans-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/aurora-humans-container:latest'
      - '--region'
      - 'asia'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

  # Step 5: Set up the API Gateway
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'apigateway'
      - 'api-configs'
      - 'create'
      - 'my-config'
      - '--api'
      - 'my-api'
      - '--openapi-spec'
      - 'path/to/openapi.yaml'

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'apigateway'
      - 'gateways'
      - 'create'
      - 'aurora-gateway'
      - '--api'
      - 'my-api'
      - '--api-config'
      - 'my-config'
      - '--location'
      - 'asia'

substitutions:
  _REGION: asia
  _SERVICE_NAME: aurora-humans-app

images:
  - 'gcr.io/$PROJECT_ID/aurora-humans-container:latest'
