version: '3.8'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/path/to/your-service-account-file.json
    volumes:
      - .:/app