swagger: "2.0"
info:
  title: "API Gateway for Streamlit App"
  description: "API Gateway configuration"
  version: "1.0.0"
paths:
  /:
    get:
      x-google-backend:
        address: https://{service_status_url}
      responses:
        '200':
          description: "A successful response"