api_spec=""
swagger: "2.0"
info:
  title: "Streamlit App API"
  description: "API Gateway for Streamlit App"
  version: "1.0.0"
paths:
  /:
    get:
      x-google-backend:
        address: https://
      responses:
        '200':
          description: "A successful response"
  /health:
    get:
      description: "Health check endpoint"
      x-google-backend:
        address: https://your-cloud-run-service-url/health
      responses:
        '200':
          description: "Service is healthy"
          schema:
            type: string
        '500':
          description: "Service is unhealthy"
          schema:
            type: string
# Uncomment the following block to set up streaming data through Dataflow and Pub/Sub
# paths:
#   /stream:
#     post:
#       description: "Stream data through Dataflow and Pub/Sub"
#       x-google-backend:
#         address: https://your-dataflow-service-url
#       parameters:
#         - name: "data"
#           in: "body"
#           description: "Data to be streamed"
#           required: true
#           schema:
#             type: "object"
#             properties:
#               field1:
#                 type: "string"
#               field2:
#                 type: "string"
#       responses:
#         '200':
#           description: "Data streamed successfully"
#           schema:
#             type: "string"
#         '400':
#           description: "Invalid input data"
#           schema:
#             type: "string"
"""

with open("gateway_config.yaml", "w") as f:
    f.write(api_spec)
