version: 2.1

orbs:
  docker: circleci/docker@2.6.0

executors:
  python-executor:
    environment:
       GCLOUD_SERVICE_KEY: $GCLOUD_SERVICE_KEY
       HOME: $HOME
    docker:
      - image: cimg/python:3.12.3
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_ACCESS_TOKEN
    working_directory: ~/app/

jobs:
  setup:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install Google Cloud SDK
          command: |
            sudo apt-get update
            sudo apt-get install -y apt-transport-https ca-certificates gnupg
            echo "deb https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
            sudo apt-get update && sudo apt-get install -y google-cloud-sdk
      - run:
          name: Authenticate with GCP
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud config set project your-gcp-project-id

  build:
    executor: python-executor
    steps:
      - setup_remote_docker:
          version: 20.10.7
      - checkout
      - run:
          name: Docker Login
          command: echo "$DOCKER_ACCESS_TOKEN" | docker login --username "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Install Dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t $DOCKER_USERNAME/aurora-humans-app:latest .
            docker push $DOCKER_USERNAME/aurora-humans-app:latest

  pulumi-preview:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install Pulumi
          command: curl -fsSL https://get.pulumi.com | sh
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Pulumi stack select
          command: pulumi stack select dev
      - run:
          name: Pulumi preview
          command: pulumi preview --yes

  pulumi-deploy:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install Pulumi
          command: curl -fsSL https://get.pulumi.com | sh
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Pulumi stack select
          command: pulumi stack select dev
      - run:
          name: Pulumi deploy
          command: pulumi up --yes

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - setup
      - build:
          requires:
            - setup
      - pulumi-preview:
          requires:
            - build
      - pulumi-deploy:
          requires:
            - pulumi-preview
